[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { typescript = { tsdk = "/home/satyamm09/.local/share/pnpm/global/5/node_modules/typescript/lib" } }

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
language-servers = ["astro-ls"]
# formatter = { command = "prettier", args = [
#   "--plugin",
#   "prettier-plugin-astro",
#   "--parser",
#   "astro",
# ] }
auto-format = true

[[language]]
name = "toml"
auto-format = true


[[language]]
name = "typescript"
auto-format = true
